# Generated by Django 3.2.25 on 2026-06-03 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=15)),
                ('date_match', models.DateTimeField(auto_now_add=True)),
                ('objectif', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('email_ifri', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('promo', models.CharField(max_length=10)),
                ('filiere', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('mentore', 'Mentoré'), ('les_deux', 'Les deux')], max_length=10)),
                ('mot_de_passe_hash', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_session', models.DateTimeField()),
                ('duree', models.IntegerField()),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('faite', 'Faite'), ('annulee', 'Annulée')], default='planifiee', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.utilisateur')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_mentor', to='core.utilisateur'),
        ),
        migrations.AddField(
            model_name='match',
            name='mentore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_mentore', to='core.utilisateur'),
        ),
        migrations.CreateModel(
            name='UserCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField(blank=True, null=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.utilisateur')),
            ],
            options={
                'unique_together': {('user', 'competence')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('mentor', 'mentore')},
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.utilisateur')),
            ],
            options={
                'unique_together': {('mentor', 'jour', 'heure_debut')},
            },
        ),
    ]
