# Generated by Django 3.2.25 on 2026-06-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='points_faibles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='points_forts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
