# Generated by Django 3.2.25 on 2026-06-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260604_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_offre', models.CharField(choices=[('offre', 'Offre de mentorat'), ('demande', 'Demande de mentorat')], max_length=10)),
                ('competences', models.TextField()),
                ('disponibilites', models.TextField()),
                ('format', models.CharField(choices=[('presentiel', 'Présentiel'), ('enligne', 'En ligne'), ('les_deux', 'Les deux')], default='les_deux', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.utilisateur')),
            ],
        ),
    ]
