# Generated by Django 3.2.25 on 2026-06-08 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_offre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilite',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='core.utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('mentore', 'Mentoré'), ('les_deux', 'Les deux')], default='mentore', max_length=10),
        ),
        migrations.CreateModel(
            name='DisponibiliteMentore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('mentore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites_mentore', to='core.utilisateur')),
            ],
            options={
                'db_table': 'disponibilites_mentores',
                'unique_together': {('mentore', 'jour', 'heure_debut')},
            },
        ),
    ]
